name: Test Database Tool
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Evagram Input Module
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Checkout Evagram Repository
        uses: actions/checkout@v2
        with:
          repository: JCSDA-internal/evagram
          ref: feature/evagram_input_testing

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Test Script
        run: python src/evagram/website/backend/manage.py test api.test_input_tool
